sudo: required
language: node_js
dist: trusty
node_js:
  - '8'
services:
  - node

branches:
  except:
    - /^pr\..*/
    - /^features\..*/
  only:
    - master
    - develop
    - /^v[0-9]+\.){0,2}(\*|[0-9]+

before_install:
  - git clone https://github.com/djanta/travis-npm-deploy.git ~/travis-npm-deploy
  - chmod +x ~/travis-npm-deploy/deploy.sh && chmod +x ~/travis-npm-deploy/npm/*.sh
  - bash ~/travis-npm-deploy/deploy.sh --git-config

install:
  - echo "Installing ..."
  - bash ~/travis-npm-deploy/deploy.sh --install

script:
  - echo "Npm deploy email= $NPM_EMAIL"

after_script:
  - echo "Runing after script djantajs bundle ..."

after_success:
  - echo "Running after success step ..."

before_deploy:
  - echo "Running before deploy step ..."
  - bash ~/travis-npm-deploy/deploy.sh login --user=$NPM_USER --password=$NPM_PWD --email=$NPM_EMAIL

deploy:
  -
    provider: script
    skip_cleanup: true
    email: "$NPM_EMAIL"
    script: ~/travis-npm-deploy/deploy.sh
    on:
      tags: true
      repo: djanta/djantajs-compose

after_deploy:
  - echo "Running after deploy step ..."
  - bash ~/travis-npm-deploy/deploy.sh logout

notifications:
  email: false
  slack:
    rooms:
      - djantaio:1GeeSv1noSekK9to1yTqsbDw#travis-ci
      - djantaio:1GeeSv1noSekK9to1yTqsbDw#djantajs
      - djantaio:1GeeSv1noSekK9to1yTqsbDw#tools
    on_success: always
    template:
      - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch}
        by %{author} %{result} in %{duration}
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/527ecb157afe8c3f6eb9
    on_success: change
    on_failure: always
    on_start: never
