sudo: required
language: node_js
dist: trusty
node_js:
  - '8'
branches:
  except:
    - /^pr\\..*/"=
    - "/^features\\\\..*/"
before_install:
  - git clone https://github.com/djanta/travis-npm-deploy.git ~/travis-npm-deploy
  - chmod +x ~/travis-npm-deploy/deploy.sh && chmod +x ~/travis-npm-deploy/npm/*.sh
  - bash ~/travis-npm-deploy/deploy.sh --git-config
install:
  - bash ~/travis-npm-deploy/deploy.sh --install
  - npm i --verbose
  - 'echo "repo_token: $COVERALLS_REPO_TOKEN" > "./.coveralls.yml"'
  - npm run-script snyk-login -- $SNYK_TOKEN
script:
  - npm test
after_script:
  # - npm run-script coverage-push
after_success:
  - npm run-script snyk-monitor
  - npm run-script coverage
before_deploy:
  - bash ~/travis-npm-deploy/deploy.sh login --user=$NPM_USER --password=$NPM_PWD --email=$NPM_EMAIL
deploy:
  - provider: script
    skip_cleanup: true
    email: "$NPM_EMAIL"
    script: "~/travis-npm-deploy/deploy.sh"
    on:
      tags: true
      repo: djanta/djantajs-compose
after_deploy:
  - echo "Running after deploy step ..."
  - bash ~/travis-npm-deploy/deploy.sh logout
notifications:
  email: false
  slack:
    rooms:
      - djantaio:1GeeSv1noSekK9to1yTqsbDw#travis-ci
      - djantaio:1GeeSv1noSekK9to1yTqsbDw#djantajs
    on_success: always
    template:
      - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch}
        by %{author} %{result} in %{duration}
  webhooks:
    urls:
      - "$WEBHOOK_GITTER"
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
    - secure: hiUAyDzPyy2QjTgR4C0PjxBHYz698yWe/DnYR7TlqTYJId+MGKS90RZB1k42DLRQ6T+PzCM05HJmzAdk45YeGCsPm2jGBnGdIsO83MbKzItCD215YvaA4DndOUTeLBBPOLmMnsJDGvRn1oz5qD6SPDbuZMk4eW2qVXOqqe9eQogCWnCnF15WiGwo1jUwfPQJoG7qU0vkhEuGZOcopJWy9joD2pBultJPc0Xat4F0Ts04nf/zYRFbEEPcJOmhiVY/le45Z74vrVwAQIIoVdd8hJVVm/mnr75CblPSZpOrRM0r1p1kmIQaEy1Qxqbj6qL+IBuoItk3XeI/IjY0iOFskV2Jo5NnEaUvegUkDGgIJjjATR7vK+Ehl31yrsGgypwEZeDCyzI1bb2ZHUo4+P+a5Lwqx9LQG0xMlHYTo9BZFehiVfREWoAESD25kiTH4yuIEdoorMux3ErasAWjppcj663Mq7iTvALCHxi7iCb67D7T8ynAJgAI/bjYeQuqKEA9MmZGgZdIu13oiVRZEY9qgTBP5PMeQAeYI+lqX2etjih6lGRKXU4XONesRL5ZtnIQ3vdKOhe0HP935EB65kdDovlbsqqrcaFnMFC41GfTu4jf4ORmVi7tDQnitrjauAatYLQd1a9XS5p+HaSLKZdozkWxCgdwqe9TdSxBRUnnAH4=
    - secure: REN/ijR50pLBJEt6UjWglC7pkn2FA6BywWFTVbu2+/Sn5fSBVQCvgnOsOEhZpDwJ0XgP02xGpUpFvpoLkY5ymvGVPIqP23C+K76cE+gOfA17eMjcGPws46rsR4bjBKCWqWONF5j9yE1U7vTTesGacW1X+wtpgMind6tPvQLjykztCv6uHXV0hzYUw/jrsZkzqaekG3/8QmaXAx0PW7AjCqsfUNlRLXjFOOiYEhfpLs1S4ku+z5wFC6l445Nt41vbK9VQDPpJ6vvIfHXZvDP0p4/V1rmhOkP3RIMUF5Di3LDOU4lNIQ/OMoR9Tey8mbwCzvfR/XeH+PQpOLcgdYf4qUqnyRlCWn+LlxZrFYwRdqds0F+h+abOJ6tSJsF9c1/qJu1csr91yKPcZz/yw/prfzVTLgiyllKEkNK3oQxcQbNKSKnuPgkUpwT9cNCTYgnN2VWouckHweK3E4VD5sSDTtA1umN7KmHlhZa/1UDsXMzxZCEVLnMy73NNPppemqrYbAh0tWdx/AUgbW7cpDfWCnJwtjw4Vuqm/FuxqrBs96sR+THMUbO5MuJBPRRd4R9ug0FrPl3rGG7KsJ9aGnIeOWBQ2rqTu6MfFs8UZHU/p2PWDe2BvxX4BpYm7zgk1ubHYNMw3lnaIrz9AKKJnhxekQ8iB0gxCb941HI7QmW3gt0=
    - secure: OIQ97E9S5bezs+F28+lBnQxRedgz1jEn9SlSrqZXPrfKY1PMyYYtHZ66r7PADnUfnFjlxMHVKEjen+AYdD4sOwfrtfICtuLvfGdrqq57YDVP7Vl4eqdo3goD+u7q8qkTIVoCwIMJy2MOI69K4VM0ULoFttYp0afvW1xllmkHBeb5r18Uafio88VV9MUyQCN5Cemw5Y4Ild0iUj7oMDzkb0ebyR6zr4rZARRaJ8AR5FNNg8X8cv9TChn0bbYs9sTuh4K9mmz/FJa08AL7v9nvOEJ2DLvu5AXCNyd2FNrzPo1nnCpFFoUAov2/9y5O3kjEiABVJk8MAkTqWZhZObIQI11+QH7mDehjrE5HKoF4pzuqzl/hRGaWwlnKhWjVvK1KyAWoHVCNT8lE4J2wrSHUOby0pFuXVcjYzw0EiBaG/GPtuhuAd9qrdrYW7hcL6mV5J0B4/PQ4z/uWxtuzSZHQPmdnxbzQCajXFuWU/IUB1ai1WkOZd+6+fR3bimKKxoJtLn+LfuQ9KRBnuaanJVVG2yiMQq66/hqtAX2Nf+EJY8coS5BmHh0HWYO1OmyU1dxIOvEPuwAPcVOp4pz6ORwcLJerDS2myLhh8tiWZN0UIdmElpzmHbfI6DVGNPiwUPnbUfabRWepoiRULTIm3kO0KykE0/KXat2+/W6+EdSb65A=
    - secure: cev4KqqT/vH0iPYLMXmDBd95jJQ4JJsAf6yJkJvITh4VXh/m2qm/OmyXlXNrM5QMYUoJ13y+OieL4Q5rz1ZTWx0qLklT8VqiLC1hTIMUBLCPPYFF75vhHYI+J7KpGih1Yu52KBEuPkIZnnDOGJMCQiDDUr5RFP1t5EbSMpPi/BiD9CKtGYGlMoq+OTQE+rF2ZrqORYBBPkhq871vNsljPKvqTcTwdJf9tY3qU14wNunDSZ9hcS+yMLNTq+O4ivbtmLi5agZOHa110G1CuR3oWAfSNrbuAUpe4bgT0onWAY3zpTJZrwazxppcyL/j6KcS4Fz6+DXWTBiLXYpgZMGqv0qELiUr2HmvEyIQypsh8gDfeO75COb5Wk+/E7QbH0cE9vPJ8NHNCo3CQ2WgBFEDnUHWq6f/+vemb610VO8ti7MWgFUYr5jAlKT7j74r5ZobOpG4X8AU3MjDcn1z+EGmFBt5/ebCYF18lAnYRhqWGEpgztujD76Axi5sCyTZmrQuA73SC2KaWcagBOhMieTnaZEXv+M7zZ4OY02PFBJi6ogGl2sVdCevILapVfWoxyRujPhyQmF6tyqVjv1GZk7Dx4AX6JvYEV3tUX/4d/ZO8LtYZ3aKNNasiVjs1u5/TUFu862rhyR/daS4guOpjtcGkq4sA/q80Jc5VN+tnq+tEko=
    - secure: R1zkLe+4VUSIQUc6E5m/5YJouSOagRb0Qd6t6/gaVfEF4UHd/1C1r7ZvnDZXys9Is1ftp6neWW6QJFk9EQbgZUuhyCyo82OZuzrixspINf96aLFYIW4cKR50XJGciJrPdWqVL3rfTsALAchW3s/+6I4KyVQW3ZX9+x6DIXbr07WpmzwUrYG3JncYNpIk3SrZIksgVI9aKrKte3cr43WUBJdOGJKtyHiz3gBke+XYDxk3S1ZbaDV2SIMKdvcwGlunxtjhzBwrxKjlB9/XlD++JozkgGWRbkgtZ7/AOzyR3GGEWGYPfmBG0LzInielZPIEa64OJBSjDsRl02sG9HQ26/zbAKiQICb7vj/JdYUxN1YQXy//Fk2W+R9Jl1OJ+VnZXayGMpjkwW5+kTXbefEQA0SzYy7ubsK/Jp1v0oISLYuNYw9D4zBXdWrNZLwP55bLvTKFlTg57mzDx02hpfRdieEZgZv24AZgM3sC37MrPgtso1whnf9LkHIzxtud6m/Mrhp/ouw8Q47msIT1qV+mlHAkNGisfkuUGBEIXv6hQypRRjW/bYKyM9N/PqT6FnizrVK4ZQuIEj9umEmpAJRmC0KHJaIGHVZ0YzEvLQwGd5KldoNjA3K4W79DPGT+uCVEFdD5DU26CT+clJBmTmhqeynGXRA7ju0e8wq3PK1+noQ=
    - secure: QSJ/Pug/lsenm7ShkJLhO3T10CBdPxLliyBm+vMM9w1O0iqmwVCFGP7R/r+ZdGfV411FAtovxsag0Z8KiITXut1I+3rfnrCxoY9JnMyC7LCFjwhNL8lKn7Fsh4yloshR17/+ZXgW8BVQc9bY0lcOKuw6ueFnoqlaohuHJbiNe+Sk69J62OCzMwrcN/Eg4nq500MI1zqh8GUqo+sJJ+asoZbvdF+o7GgfdciKCJT78t6RwbXIPj3eBwdN6321IMn8l66jbLBnoZZH8vb4lK7ox9kQu8lTTvPEVBvmTscY4t/g2VLuD9s3X1vOuQhos7yUMIVchAN072E5GmGm4b5Iu02UhZ9t6/VTDeFLoe90Je7DVyJFTZvFSr25HIMs59/AKa2vBEp3kifDi/7/UQAljKdl9GNQmg6I5sxFQHgtlnbzZ3O5cSWYDgeClxeNvq8mOC81DUaQQ/90ugp1FH1brPmwd9kRpGZKepn1W5IXiRiIxikx2ttmcvnT5DEQa8sjnV6DLr0Q3pXlDmavS/lcHJaMMMOS5v5hLIwQ+1unyBylHgDYJ1iijeCznW1PFj5gPB+ofT5P5kfP4wo6zO9u8gQRmMMKJkUFwz0II5TGgvvog10Kr8dbaEnwgwduXJJx6FDSyQmT8VsF1/tjkXWQ4lcmYwXAPW5dewPIyBJJ9tw=
    - secure: kbAHsh57AhW2rhuOyQPyoDA/wlBkP4MhOPI23FmAYKmLNx8FOWZw8owGMAEEJ1sunSpZAEX3LrQbXY78TwRLwWKfLwoom/bqePeGBBFV6rLGYQfvb6C1+DWWAFpvOggXom2FfJ6cOXnIjQxKOz2h6CRwTPr73xnY+nC19F4oYR+XN1ly3+t0IgYceXRrQfoAvP1szH3FRHIhBiLV3lFO1KeO+vFuUbs/ju1/eY1D24q4k0gvq4I+MQSTWVk5AvWEopp/mL4n3BJwvzElfSQEw08IDM5DQza3ufhKdl4g+M4RWnuqfyMako/Qu7ttJDQvTVjPcvR7ksBfVRAlXhakzqcw7Fe1uZhziA4MUhmjwRxhkv1h1BP0lT2C9vpSbOl96gJaeBs0RrOMrNG5IL3jQ67CXnjSF7DfMW4RmPPc9Er1FzgJILUrbxJD5jlg0aKBJWXWRdPfUDyR02Xy1XHsqCeUjLvHNuZn5mMq9R8LnyW3bO0G0NZwYP43qNICjOIlYXMQxSVkgSQ4Gm7aGlDf1XV4JeazA9EWUW0fxQLFIPm6mFYqES/FIg58C6B59DDwa/6cC2qKrG+xuIOyChLJHovxFqn7OppKzNyL7s/cwC/eu0RErcQrWZnMBO/ZWIsr5nvIAT+OmuLkOJOZacPFzug6cuAH6tBOQO29b8naRPo=
