sudo: required
language: node_js
dist: trusty
node_js:
  - '8'
services:
  - node
branches:
  except:
    - "/^pr\\..*/"
    - "/^features\\..*/"
  only:
    - master
    - develop
    - "/^v[0-9]+\\.){0,2}(\\*|[0-9]+"
before_install:
  - git clone https://github.com/djanta/travis-npm-deploy.git ~/travis-npm-deploy
  - chmod +x ~/travis-npm-deploy/deploy.sh && chmod +x ~/travis-npm-deploy/npm/*.sh
  - bash ~/travis-npm-deploy/deploy.sh --git-config
install:
  - echo "Installing ..."
  - bash ~/travis-npm-deploy/deploy.sh --install
  - npm i --verbose
script:
  - echo "Npm deploy email= $NPM_EMAIL"
  - npm test
after_script:
  - echo "Runing after script djantajs bundle ..."
after_success:
  - echo "Running after success step ..."
before_deploy:
  - echo "Running before deploy step ..."
  - bash ~/travis-npm-deploy/deploy.sh login --user=$NPM_USER --password=$NPM_PWD --email=$NPM_EMAIL
deploy:
  - provider: script
    skip_cleanup: true
    email: "$NPM_EMAIL"
    script: "~/travis-npm-deploy/deploy.sh"
    on:
      tags: true
      repo: djanta/djantajs-compose
after_deploy:
  - echo "Running after deploy step ..."
  - bash ~/travis-npm-deploy/deploy.sh logout
notifications:
  email: false
  slack:
    rooms:
      - djantaio:1GeeSv1noSekK9to1yTqsbDw#travis-ci
      - djantaio:1GeeSv1noSekK9to1yTqsbDw#djantajs
      - djantaio:1GeeSv1noSekK9to1yTqsbDw#tools
    on_success: always
    template:
      - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch}
        by %{author} %{result} in %{duration}
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/527ecb157afe8c3f6eb9
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
    - secure: hiUAyDzPyy2QjTgR4C0PjxBHYz698yWe/DnYR7TlqTYJId+MGKS90RZB1k42DLRQ6T+PzCM05HJmzAdk45YeGCsPm2jGBnGdIsO83MbKzItCD215YvaA4DndOUTeLBBPOLmMnsJDGvRn1oz5qD6SPDbuZMk4eW2qVXOqqe9eQogCWnCnF15WiGwo1jUwfPQJoG7qU0vkhEuGZOcopJWy9joD2pBultJPc0Xat4F0Ts04nf/zYRFbEEPcJOmhiVY/le45Z74vrVwAQIIoVdd8hJVVm/mnr75CblPSZpOrRM0r1p1kmIQaEy1Qxqbj6qL+IBuoItk3XeI/IjY0iOFskV2Jo5NnEaUvegUkDGgIJjjATR7vK+Ehl31yrsGgypwEZeDCyzI1bb2ZHUo4+P+a5Lwqx9LQG0xMlHYTo9BZFehiVfREWoAESD25kiTH4yuIEdoorMux3ErasAWjppcj663Mq7iTvALCHxi7iCb67D7T8ynAJgAI/bjYeQuqKEA9MmZGgZdIu13oiVRZEY9qgTBP5PMeQAeYI+lqX2etjih6lGRKXU4XONesRL5ZtnIQ3vdKOhe0HP935EB65kdDovlbsqqrcaFnMFC41GfTu4jf4ORmVi7tDQnitrjauAatYLQd1a9XS5p+HaSLKZdozkWxCgdwqe9TdSxBRUnnAH4=
    - secure: REN/ijR50pLBJEt6UjWglC7pkn2FA6BywWFTVbu2+/Sn5fSBVQCvgnOsOEhZpDwJ0XgP02xGpUpFvpoLkY5ymvGVPIqP23C+K76cE+gOfA17eMjcGPws46rsR4bjBKCWqWONF5j9yE1U7vTTesGacW1X+wtpgMind6tPvQLjykztCv6uHXV0hzYUw/jrsZkzqaekG3/8QmaXAx0PW7AjCqsfUNlRLXjFOOiYEhfpLs1S4ku+z5wFC6l445Nt41vbK9VQDPpJ6vvIfHXZvDP0p4/V1rmhOkP3RIMUF5Di3LDOU4lNIQ/OMoR9Tey8mbwCzvfR/XeH+PQpOLcgdYf4qUqnyRlCWn+LlxZrFYwRdqds0F+h+abOJ6tSJsF9c1/qJu1csr91yKPcZz/yw/prfzVTLgiyllKEkNK3oQxcQbNKSKnuPgkUpwT9cNCTYgnN2VWouckHweK3E4VD5sSDTtA1umN7KmHlhZa/1UDsXMzxZCEVLnMy73NNPppemqrYbAh0tWdx/AUgbW7cpDfWCnJwtjw4Vuqm/FuxqrBs96sR+THMUbO5MuJBPRRd4R9ug0FrPl3rGG7KsJ9aGnIeOWBQ2rqTu6MfFs8UZHU/p2PWDe2BvxX4BpYm7zgk1ubHYNMw3lnaIrz9AKKJnhxekQ8iB0gxCb941HI7QmW3gt0=
    - secure: OIQ97E9S5bezs+F28+lBnQxRedgz1jEn9SlSrqZXPrfKY1PMyYYtHZ66r7PADnUfnFjlxMHVKEjen+AYdD4sOwfrtfICtuLvfGdrqq57YDVP7Vl4eqdo3goD+u7q8qkTIVoCwIMJy2MOI69K4VM0ULoFttYp0afvW1xllmkHBeb5r18Uafio88VV9MUyQCN5Cemw5Y4Ild0iUj7oMDzkb0ebyR6zr4rZARRaJ8AR5FNNg8X8cv9TChn0bbYs9sTuh4K9mmz/FJa08AL7v9nvOEJ2DLvu5AXCNyd2FNrzPo1nnCpFFoUAov2/9y5O3kjEiABVJk8MAkTqWZhZObIQI11+QH7mDehjrE5HKoF4pzuqzl/hRGaWwlnKhWjVvK1KyAWoHVCNT8lE4J2wrSHUOby0pFuXVcjYzw0EiBaG/GPtuhuAd9qrdrYW7hcL6mV5J0B4/PQ4z/uWxtuzSZHQPmdnxbzQCajXFuWU/IUB1ai1WkOZd+6+fR3bimKKxoJtLn+LfuQ9KRBnuaanJVVG2yiMQq66/hqtAX2Nf+EJY8coS5BmHh0HWYO1OmyU1dxIOvEPuwAPcVOp4pz6ORwcLJerDS2myLhh8tiWZN0UIdmElpzmHbfI6DVGNPiwUPnbUfabRWepoiRULTIm3kO0KykE0/KXat2+/W6+EdSb65A=
